[project]
name = "proxy-sing-box"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "curl-cffi>=0.13.0",
    "lxml>=6.0.0",
    "requests>=2.32.4",
]
