[project]
name = "proxy-sing-box"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "aiohttp>=3.12.15",
    "lxml>=6.0.1",
    "pyarmor>=9.1.8",
]
