PROXY_HOST = "192.168.2.109"
PROXY_PORT = 10808
PROXIES = {
    "http": f"http://{PROXY_HOST}:{PROXY_PORT}",
    "https": f"http://{PROXY_HOST}:{PROXY_PORT}"
}
# PROXIES = None
PROXIES_ASYNC = f"http://{PROXY_HOST}:{PROXY_PORT}"

SING_BOX_PATH = "./sing-box"
OUT_LISTEN_PORT = 1080
TEST_LISTEN_PORT = 10800
SPEED_LIMIT = 2000

