name: Timed Scheduling
on:
  workflow_dispatch:
  push:
    branches: [ main,master ]
#    paths:
#      - '.github/workflows/build.yml'
  schedule:
    - cron: '0 * * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04

    env:
      DEBIAN_FRONTEND: noninteractive
      TZ: Asia/Shanghai

    steps:
      - name: Install system dependencies
        run: |
          apt-get update && apt-get install -y \
          curl \
          git \
          && apt-get clean \
          && rm -rf /var/lib/apt/lists/*

      - uses: actions/checkout@v4

      - name: RUN AND PUSH NODES
        shell: bash -l {0}
        run:
          ./main

      - name: Commit and Push
        run: |
          git config --global --add safe.directory '*'
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update execution log [skip ci]" || exit 0
          git push

      - name: Create summary
        run: |
          echo "### 🎉 Build Successful" >> $GITHUB_STEP_SUMMARY